#!/bin/bash
#┌─────────────────────┐
#│ Версия по умолчанию │
#└─────────────────────┘
    IMAGE_NAME='c9js/c9docker:1.0.26'
    if [[ $1 != '' ]]; then
        IMAGE_NAME="c9js/c9docker:$1"
    fi
    
#┌────────────────────┐
#│ Выводим имя образа │
#└────────────────────┘
echo "Образ '$IMAGE_NAME'"
    
#┌────────────────────────────────┐
#│ Останавливаем старый контейнер │
#└────────────────────────────────┘
clear
echo "Starting '$IMAGE_NAME'"
echo "[1/2] Stopping..."
docker stop $(docker ps -aq --filter "ancestor=$IMAGE_NAME")

#┌──────────────────────────┐
#│ Удаляем старый контейнер │
#└──────────────────────────┘
clear
echo "Starting '$IMAGE_NAME'"
echo "[2/2] Cleaning..."
docker rm $(docker ps -aq --filter "ancestor=$IMAGE_NAME")

#┌─────────────────────┐
#│ Запускаем контейнер │
#└─────────────────────┘
./run 8000 c9manager c9js $IMAGE_NAME
