#!/bin/bash
#┌──────────────────────┐
#│ Загружаем библиотеки │
#└──────────────────────┘
. ~/cli/lib.base
. ~/cli/lib.filesystem
. ~/cli/lib.docker
. ~/cli/lib.stream
. ~/cli/gui.menu
. ~/cli/gui.input
. ~/cli/gui.notice

#┌───────────────┐
#│ Загружаем MVC │
#└───────────────┘
# Models
. /models/modelAPI
. /models/modelMenu
. /models/modelNotice
. /models/modelDocker
. /models/modelRequest
. /models/modelRun

# Entrypoints
. /entrypoints/entrypointAPI
. /entrypoints/entrypointMenu

# Controllers
. /controllers/controllerMenu
. /controllers/controllerNotice
. /controllers/controllerDocker
. /controllers/controllerRequest
. /controllers/controllerRun

# Views
. /views/view
. /views/viewMenu
. /views/viewNotice

#┌───────────────────────────────────────────────┐
#│ Путь к текущему каталогу вне docker-а         │
#├───────────────────────────────────────────────┤
#│ Конвертируем:                                 │
#│ Путь Windows -> "D:\MyProjects\project"       │
#│ в путь Linux -> "/d/MyProjects/project"       │
#│ 1. Переводим первый символ в нижний регистр   │
#│ 2. Переводим обратные слешы "\" в "/"         │
#│ 3. Добавляем в начало "/", (если его там нет) │
#│ 4. Удаляем ":"                                │
#└───────────────────────────────────────────────┘
DOCKER_PWD=$(echo "$CD" | sed \
    -e 's/[A-Z]/\L&/' \
    -e 's-\\-\/-g' \
    -e '/^\//!s-^-/-' \
    -e 's-:--' \
)

#┌─────────────┐
#│ Разделитель │
#└─────────────┘
[[ "${CD/\\}" != "$CD" ]] && SEP='\' || SEP='/'

#┌───────────────────┐
#│ Список переменных │
#└───────────────────┘
PATH_VERSION='VERSION'                 # Путь к файлу где хранится номер версии
PATH_GIT_USER='.c9/pwd/git_user'       # Путь к файлу где хранится имя git-юзера
PATH_GIT_REPO='.c9/pwd/git_repo'       # Путь к файлу где хранится имя git-репозитория
PATH_DOCKER_USER='.c9/pwd/docker_user' # Путь к файлу где хранится логин от docker-репозитория
PATH_DOCKER_PASS='.c9/pwd/docker_pass' # Путь к файлу где хранится пароль от docker-репозитория

SSH_DIR='ssh'             # Путь к каталогу где хранятся ssh-ключи
CURRENT_PATH='/root/repo' # Путь к текущему каталогу из docker-а
GIT_URL='github.com'      # URL git-репозитория
PORT_DEFAULT='8000'       # (по умолчанию) Порт
DOCKER_USER='c9js'        # (по умолчанию) Логин от docker-репозитория
GIT_USER='c9js'           # (по умолчанию) Имя git-юзера
GIT_REPO='c9manager'      # (по умолчанию) Имя git-репозитория
WORKSPACE='c9manager'     # (по умолчанию) Имя рабочего каталога
IMAGE_RUN='c9js/c9docker' # Имя образа который запускаем
IMAGE_API='c9js/c9start'  # Имя текущего образа
# IMAGE_DEV='c9start'     # Имя текущего образа для тестирования
IMAGES=(                  # Список всех образов
    'c9js/c9docker'
    'c9js/c9start'
    'c9js/c9open'
    'c9docker'
    'c9start'
    'c9open'
)

#┌─────────────────────────┐
#│ Загружаем версию образа │
#└─────────────────────────┘
VERSION="$(get_file "$HOME/$PATH_VERSION")"

#┌─────────────┐
#│ Точки входа │
#└─────────────┘
case "$1" in
    'API') entrypoint:API "$@" ;; # Внутренний запрос
    *)     entrypoint:Menu     ;; # Меню
esac
