#!/bin/bash
#┌───────────────┐
#│ Версия образа │
#└───────────────┘
VERSION='1.0.36'

#┌──────────────────────┐
#│ Загружаем библиотеки │
#└──────────────────────┘
. ~/cli/lib.base
. ~/cli/lib.docker
. ~/cli/gui.menu
. ~/cli/gui.input
. ~/cli/gui.notice

#┌───────────────┐
#│ Загружаем MVC │
#└───────────────┘
# Models
. /models/modelAPI
. /models/modelMenu
. /models/modelDocker
. /models/modelRequest

# Entrypoints
. /entrypoints/entrypointAPI
. /entrypoints/entrypointMenu

# Controllers
. /controllers/controllerMenu
. /controllers/controllerDocker
. /controllers/controllerRequest

# Views
. /views/view
. /views/viewMenu

#┌───────────────────────────────────────────────┐
#│ Путь к текущему каталогу вне docker-а         │
#├───────────────────────────────────────────────┤
#│ Конвертируем:                                 │
#│ Путь Windows -> "D:\MyProjects\project"       │
#│ в путь Linux -> "/d/MyProjects/project"       │
#│ 1. Переводим первый символ в нижний регистр   │
#│ 2. Переводим обратные слешы "\" в "/"         │
#│ 3. Добавляем в начало "/", (если его там нет) │
#│ 4. Удаляем ":"                                │
#└───────────────────────────────────────────────┘
DOCKER_PWD=$(echo "$CD" | sed \
    -e 's/[A-Z]/\L&/' \
    -e 's-\\-\/-g' \
    -e '/^\//!s-^-/-' \
    -e 's-:--' \
)

#┌───────────────────┐
#│ Список переменных │
#└───────────────────┘
GIT_USER='c9js'           # Имя git-юзера
PORT_DEFAULT='8000'       # Порт по умолчанию
GIT_URL='github.com'      # URL git-репозитория
PROJECT_NAME='c9manager'  # Имя проекта
CURRENT_PATH='/root/repo' # Путь к текущему каталогу из docker-а
IMAGE_RUN='c9js/c9docker' # Имя образа который запускаем
IMAGE_API='c9js/c9start'  # Имя текущего образа
# IMAGE_DEV='c9start'     # Имя текущего образа для тестирования
IMAGES=(                  # Список всех образов
    'c9js/c9docker'
    'c9js/c9start'
    'c9js/c9open'
    'c9docker'
    'c9start'
    'c9open'
)

#┌─────────────┐
#│ Точки входа │
#└─────────────┘
case "$1" in
    'API') entrypoint:API "$2" ;; # Внутренний запрос
    *)     entrypoint:Menu     ;; # Меню
esac
