#!/bin/bash
#┌──────────────────────┐
#│ Загружаем библиотеку │
#└──────────────────────┘
. ~/lib

#┌───────────────┐
#│ Версия образа │
#└───────────────┘
IMAGE_NAME='c9js/c9docker:latest'

# Создаем пункты меню
menuItems=(
#    Цвет        Строка
    'Yellow' "1. Restart    Перезагрузить '$IMAGE_NAME'"
    'Yellow' "2. Stop       Остановить '$IMAGE_NAME'"
    'Yellow' '3. Uninstall  Перейти в раздел'
      'Gray' '0. Exit'
)

# Выводим меню на экран
menu 'Выберите команду:' 1

# Очищаем экран
reset

# Выбран пункт: "Exit"
    if is_exit; then
        echo 'Exit init!'
        exit # Завершение процесса
    fi
    
# Выбранный порт
echo $REPLY

exit
Что такое Start
    Это ./start
    А вообще как таковой старт лучше не делать,
    а сразу сделать Restart
  
Что такое Stop
Нужно получить список всех ID образов
    docker images -q 'c9js/c9docker'
Далее через цикл например for() пройти по каждому контейнеру отдельно!
    docker ps --filter "ancestor=2530806c5184"
    