#!/bin/bash
#┌──────────────────────┐
#│ Загружаем библиотеку │
#└──────────────────────┘
. ~/lib

#┌───────────────┐
#│ Версия образа │
#└───────────────┘
IMAGE_NAME='c9js/c9docker:latest'

# Создаем пункты меню
menuItems=(
#    Цвет       Строка
    'Green' "1. Install  Установить '$IMAGE_NAME'"
     'Gray' '0. Exit'
)

# Выводим меню на экран
menu 'Выберите команду:' 1

# Очищаем экран
reset

# Выбран пункт: "Exit"
    if is_exit; then
        echo 'Exit init!'
        exit # Завершение процесса
    fi
    
# Выбранный порт
echo $REPLY

exit
Чтобы проверить
    "1. Install  Установить '$IMAGE_NAME'"
Должно вернуть ноль(=0) id образов
    docker images -q 'c9js/c9docker'
    